name: LuckRank
version: ${version}
main: de.pcblc.spigot.LuckRankSpigot
author: ${author}
depend:
  - LuckPerms
commands:
  rank:
    description: Verwalte LuckPerms-Raenge und Rechte
    aliases:
      - r
