name: LuckRank
version: 2.3
main: de.pcblc.spigot.LuckRankSpigot
author: pcblc
api-version: "1.13"
softdepend:
  - LuckPerms
commands:
  rank:
    description: Verwalte LuckPerms-Raenge und Rechte
    aliases:
      - r
